const animals = [
    { name: "Max", breed: "Dog", age: "2 years", description: "A friendly and energetic German Shepherd who loves to play fetch and go for long walks." },
    { name: "Whiskers", breed: "Cat", age: "3 years", description: "A lazy Persian cat who enjoys napping in the sun and getting belly rubs." },
    { name: "Bella", breed: "Cow", age: "5 years", description: "A gentle Jersey cow that provides fresh milk every day." },
    { name: "Rocky", breed: "Goat", age: "1 year", description: "A playful Nubian goat who loves climbing rocks and eating leaves." },
    { name: "Fluffy", breed: "Sheep", age: "4 years", description: "A fluffy Merino sheep with a thick wool coat and a calm nature." },
    { name: "BunBun", breed: "Rabbit", age: "6 months", description: "A small Holland Lop rabbit that loves munching on carrots." },
    { name: "Charlie", breed: "Dog", age: "1 year", description: "A Golden Retriever puppy full of energy and excitement." },
    { name: "Mittens", breed: "Cat", age: "5 years", description: "A British Shorthair cat that enjoys cuddles and watching birds." },
    { name: "Daisy", breed: "Cow", age: "6 years", description: "A strong and healthy Holstein cow that produces high-quality milk." },
    { name: "Coco", breed: "Goat", age: "2 years", description: "A curious Pygmy goat who is always exploring new places." },
    { name: "Wooly", breed: "Sheep", age: "3 years", description: "A Dorset sheep known for its friendly personality and fluffy wool." },
    { name: "Thumper", breed: "Rabbit", age: "1 year", description: "A quick and energetic Netherland Dwarf rabbit." },
    { name: "Rex", breed: "Dog", age: "4 years", description: "A protective Doberman who is loyal and intelligent." },
    { name: "Simba", breed: "Cat", age: "2 years", description: "A mischievous Siamese cat that loves to play hide and seek." },
    { name: "Bessie", breed: "Cow", age: "7 years", description: "An Angus cow that enjoys grazing in open fields." },
    { name: "Ziggy", breed: "Goat", age: "3 years", description: "A Saanen goat who is social and enjoys human interaction." },
    { name: "Snowball", breed: "Sheep", age: "5 years", description: "A Suffolk sheep that has a thick wool coat and a kind nature." },
    { name: "Oreo", breed: "Rabbit", age: "8 months", description: "A white Flemish Giant rabbit with a sweet personality." },
    { name: "Buddy", breed: "Dog", age: "2 years", description: "A Border Collie who loves herding sheep and playing frisbee." },
    { name: "Luna", breed: "Cat", age: "4 years", description: "A Maine Coon cat with a majestic fur coat and gentle nature." },
    { name: "Buttercup", breed: "Cow", age: "3 years", description: "A Brown Swiss cow known for her docile temperament." },
    { name: "Pepper", breed: "Goat", age: "4 years", description: "A LaMancha goat with a strong and playful personality." },
    { name: "Cloud", breed: "Sheep", age: "6 years", description: "A Texel sheep that enjoys grazing in peaceful pastures." },
    { name: "Mochi", breed: "Rabbit", age: "10 months", description: "A French Lop rabbit with floppy ears and a love for cuddles." },
    { name: "Duke", breed: "Dog", age: "3 years", description: "A Boxer who is protective yet affectionate." },
    { name: "Oliver", breed: "Cat", age: "6 years", description: "A Ragdoll cat that loves to be carried around and pampered." },
    { name: "Maple", breed: "Cow", age: "8 years", description: "A Guernsey cow that produces rich, golden milk." },
    { name: "Chico", breed: "Goat", age: "2 years", description: "A Boer goat that is full of energy and enjoys playing in the field." },
    { name: "Fleece", breed: "Sheep", age: "4 years", description: "A Cheviot sheep with a thick fleece and a calm demeanor." },
    { name: "Hazel", breed: "Rabbit", age: "7 months", description: "A Havana rabbit that loves exploring new places." },
    { name: "Hunter", breed: "Dog", age: "5 years", description: "A Beagle who enjoys following scents and going on adventures." },
    { name: "Shadow", breed: "Cat", age: "1 year", description: "A playful Bengal cat with striking markings." },
    { name: "Rosie", breed: "Cow", age: "9 years", description: "A Dexter cow known for her small size and friendly nature." },
    { name: "Mocha", breed: "Goat", age: "3 years", description: "An Alpine goat that is friendly and loves to climb." },
    { name: "Marshmallow", breed: "Sheep", age: "2 years", description: "A Romney sheep with a soft and woolly coat." },
    { name: "Snickers", breed: "Rabbit", age: "5 months", description: "A Lionhead rabbit with a fluffy mane and playful spirit." },
    { name: "Cooper", breed: "Dog", age: "6 years", description: "A Poodle known for its intelligence and friendly personality." },
    { name: "Milo", breed: "Cat", age: "3 years", description: "A Scottish Fold cat with adorable folded ears." },
    { name: "Holly", breed: "Cow", age: "4 years", description: "An Ayrshire cow with a strong build and great milk production." },
    { name: "Bambi", breed: "Goat", age: "5 years", description: "A Toggenburg goat that loves being around people." },
    { name: "Blizzard", breed: "Sheep", age: "7 years", description: "A Blackface sheep that enjoys the company of other animals." },
    { name: "Domino", breed: "Rabbit", age: "9 months", description: "A Dutch rabbit with distinctive black-and-white markings." }
  ];
  
  export default animals;
  